// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swhyewxujmchwdwikhap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3aHlld3h1am1jaHdkd2lraGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDYxMzksImV4cCI6MjA2NDI4MjEzOX0.kmEmMtyWEJ3h8f7rKz07zMtpM07ev2M7fnkCswc12cM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});